version: "3"
services:
  db:
    image: postgres
    container_name: bookrentpgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentpbookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_bookrent:/var/lib/postgresql/data
  bookrent:
    image: dpage/pgadmin4
    container_name: bookrent
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
  # app:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #     target: development
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - db
volumes:
  postgres_data_bookrent:
